### ISSUE TITLE
Could not get access token

### ISSUE THREAD

**Issue by ketavc** [Happyr/LinkedIn-API-client#100]
I'm getting one big issue.

    _Could not get access token
    500 Internal Server Error - LinkedInApiException_

I'm attaching Screen shot of Error page.
![selection_004](https://cloud.githubusercontent.com/assets/7146539/15389064/a689953a-1dd2-11e6-9134-1b4a9ef6fdf1.png)

**Comment by Nyholm** [comment]
Hey @ketavc, 
There is no need of posting you comments in multiple places. I and everybody else will see you comment even though you just post it once. 

It seams like an exception is thrown from row 376. Just 2 rows above it (still on your screenshot) it says why the exception is thrown. 

If you are using the latest version of the library you will get a more detailed exception message that explains what you are doing wrong.

**Comment by ketavc** [comment]
@Nyholm 
Do you know reason behind getting this kind of error?
`Could not get access token
500 Internal Server Error - LinkedInApiException_`

**Comment by Nyholm** [comment]
> If you are using the latest version of the library you will get a more detailed exception message that explains what you are doing wrong.
