### ISSUE TITLE
Trying to get login url, get session error

### ISSUE THREAD

**Issue by mbarwick83** [Happyr/LinkedIn-API-client#101]
I'm using the Laravel 5 package. But it's just a wrapper. When I'm trying to generate login url, I'm getting the fooling error...

```
session_start(): open(/var/lib/php/sessions/sess_g009u0krgt2opthh5cmf4man60, O_RDWR) failed: Permission denied (13)
```

Any ideas as to why?

**Comment by Nyholm** [comment]
Only seeing the error messages tells me that you do not have permissions to open the file. 
Are you using the Illuminate storage? https://github.com/Happyr/LinkedIn-API-client#use-different-session-classes

**Comment by Nyholm** [comment]
Closed because inactivity.
