### ISSUE TITLE
Guzzle update

### ISSUE THREAD

**Issue by 42antoine** [Happyr/LinkedIn-API-client#102]
Could you update the guzzle package to ~6.0 ? https://github.com/artesaos/laravel-linkedin/issues/1

**Comment by 42antoine** [comment]
Tests failed on PHP 5.4 https://github.com/Happyr/LinkedIn-API-client/pull/103

Could you manage a branch based on PHP > 5.4 with Guzzle 6 ?

**Comment by 42antoine** [comment]
http://php.net/supported-versions.php

**Comment by Nyholm** [comment]
The latest version of this package is not coupled to any version of Guzzle. It is using the client abstraction from php-http. 
Read the readme to understand how you install guzzle 6

**Comment by 42antoine** [comment]
Ok, didn't catch the way to use Guzzle 6 at the first time.

Like said in readme :

First install 

```
require php-http/guzzle6-adapter
```

Then

```
require happyr/linkedin-api-client
```

Working fine.
