### ISSUE TITLE
Using new oAuth login page

### ISSUE THREAD

**Issue by mbarwick83** [Happyr/LinkedIn-API-client#104]
Any plans on updating the `getLoginUrl` function to use the newer LinkedIn oAuth login page? On Ln 205 on Linkedin.php, all that would need to be changed is `'uas/oauth2/authorization',` to `'oauth/v2/authorization',`

It'd be good to be using LinkedIn's new user experience.

**Comment by Nyholm** [comment]
Cool. I have not seen that. Please send a pull request and I'll be happy to try it out.

**Comment by mbarwick83** [comment]
Hmm, I'm using the Laravel version. Soiled I submit pull request there? `linked.php` file is quite different. I though the Laravel version was a wrapper...?

**Comment by mauri870** [comment]
Yes, send a pull here ;)

**Comment by mbarwick83** [comment]
Done and done. :)

**Comment by Nyholm** [comment]
Sweet. I'll review it once I get to a computer.

**Comment by mbarwick83** [comment]
@mauri870 It's been merged! Let me know when I can update package. Cheers.

**Comment by Nyholm** [comment]
Tagging 0.7.1 today.
