### ISSUE TITLE
How to stop connection to linkedin api once you already get the user data

### ISSUE THREAD

**Issue by mtuchi** [Happyr/LinkedIn-API-client#107]
Hello I am using this API to Register /Login new user in my application.
How to terminate the connection to linkedin once user as already signin in my app.

I have successful manage to get the user data i cant seem to disconnect with linkedin when i refresh the page. Any thoughts will be much appreciated
Thanks in advance

**Comment by Nyholm** [comment]
The user's accessToken is stored in the session. See https://github.com/Happyr/LinkedIn-API-client/blob/0.7.0/src/Authenticator.php#L72

You have to clear the session values.

**Comment by mtuchi** [comment]
Sorry for troubling you again  
can you help me with an example on how i can clear the 'access_token'

i am trying to unset the session with no lucky

below is my source code

  

&lt;?php  
  
namespace Fixd\Middleware;  
  
use Slim\Middleware;  
use Happyr\LinkedIn\LinkedIn as LinkedIn;  
  
class LinkedInMiddleware extends Middleware  
{  
 public function call()  
 {  
  
   $this-&gt;app-&gt;hook('slim.before', [$this, 'authLinkedin']);  
   $this-&gt;next-&gt;call();  
 }  
  
 public function authLinkedin()  
 {  
     $app_id = $this-&gt;app-&gt;config-&gt;get('linkedIn.app_id');  
     $app_secret = $this-&gt;app-&gt;config-&gt;get('linkedIn.app_secret');  
     $linkedIn = new LinkedIn($app_id, $app_secret);  
     $token = $linkedIn-&gt;getAccessToken();  
  
     if ($linkedIn-&gt;isAuthenticated()) {  
         //we know that the user is authenticated now. Start query the API  
         $user=$linkedIn-&gt;get('v1/people/~:(id,first-name,last-name,phone-numbers,email-address,location:(name),picture-url,industry)');  
  
         $id = $user['id'];  
         $firstName = $user['firstName'];  
         $lastName = $user['lastName'];  
         $email = $user['emailAddress'];  
         $picture = $user['pictureUrl'];  
         $industry = $user['industry'];  
         $location = $user['location']['name'];  
  
         $checkUser = $this-&gt;app-&gt;user-&gt;where('email', $email)-&gt;first();  
         if ($checkUser) {  
  
           $_SESSION[$this-&gt;app-&gt;config-&gt;get('auth.session')] = $checkUser-&gt;id;  
  
           $this-&gt;app-&gt;flash('global','Your Now loged in');  
           // unset($_SESSION['access_token']);  
           exit();  
         }else{  
           // random_hash for active_hash  
           $identifier = $this-&gt;app-&gt;randomlib-&gt;generateString(128);  
           // Use eloquent to create user  
           $user = $this-&gt;app-&gt;user-&gt;create([  
             'email'=&gt; $email,  
             'username'=&gt; $firstName,  
             'first_name'=&gt; $firstName,  
             'last_name'=&gt; $lastName,  
             'profile_pic'=&gt; $picture,  
             'password'=&gt;false,  
             'active' =&gt; false,  
             'active_hash' =&gt; $this-&gt;app-&gt;hash-&gt;hash($identifier),  
             'access_token'=&gt; $token  
           ]);  
  
           $_SESSION[$this-&gt;app-&gt;config-&gt;get('auth.session')] = $user-&gt;id;  
           exit();  
         }  
     }  
  
    elseif ($linkedIn-&gt;hasError()) {  
     echo "User canceled the login.";  
     exit();  
   }  
  
   $url = $linkedIn-&gt;getLoginUrl();  
  
   $this-&gt;app-&gt;view()-&gt;appendData([  
     'AuthUrl' =&gt; $url  
   ]);  
 }  
}  

  
Regards,

Emmanuel Evance

Ux/i Developer [@irabu](https://link.nylas.com/link/f4ajh4q3g2xdc7z2atr5d14n
/local-
8db18c95-b964/0?redirect=http%3A%2F%2Firabu.co.tz%2F&r=cmVwbHkrMDA2NDk4ZWQ0YjMzYWYzNjZmZTM2YzI1MWYxZmYyMzQwZGFmYjU0ZDhmZDA4NmUyOTJjZjAwMDAwMDAxMTM4ZDFiODA5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=)

  

![](https://link.nylas.com/open/f4ajh4q3g2xdc7z2atr5d14n/local-
8db18c95-b964?r=cmVwbHkrMDA2NDk4ZWQ0YjMzYWYzNjZmZTM2YzI1MWYxZmYyMzQwZGFmYjU0ZDhmZDA4NmUyOTJjZjAwMDAwMDAxMTM4ZDFiODA5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 30 2016, at 8:41 pm, Tobias Nyholm &lt;notifications@github.com&gt;
wrote:  

> The user's accessToken is stored in the session. See
[https://github.com/Happyr/LinkedIn-API-
client/blob/0.7.0/src/Authenticator.php#L72](https://github.com/Happyr
/LinkedIn-API-
client/blob/0.7.0/src/Authenticator.php#L72&r=cmVwbHkrMDA2NDk4ZWQ0YjMzYWYzNjZmZTM2YzI1MWYxZmYyMzQwZGFmYjU0ZDhmZDA4NmUyOTJjZjAwMDAwMDAxMTM4ZDFiODA5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=)

>

> You have to clear the session values.

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on GitHub](https://github.com/Happyr
/LinkedIn-API-
client/issues/107#issuecomment-229733555&r=cmVwbHkrMDA2NDk4ZWQ0YjMzYWYzNjZmZTM2YzI1MWYxZmYyMzQwZGFmYjU0ZDhmZDA4NmUyOTJjZjAwMDAwMDAxMTM4ZDFiODA5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe
/AGSY7fOOkv2YwwzedYiVLWEnKSF-5UgUks5qQ_-
AgaJpZM4JCYVO&r=cmVwbHkrMDA2NDk4ZWQ0YjMzYWYzNjZmZTM2YzI1MWYxZmYyMzQwZGFmYjU0ZDhmZDA4NmUyOTJjZjAwMDAwMDAxMTM4ZDFiODA5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AGSY7ZxR4hSKX99uY3Bm9g-F43SElO5Wks5qQ_-AgaJpZM4JCYVO.gif)

**Comment by Nyholm** [comment]
If you are using the SessionStorage you may do: 
```php
$session = new SessionStorage();
$session->clear('access_token');
```

**Comment by mtuchi** [comment]
Thanks so much sir  
the solution worked.  

  

Also if you could update few lines in the src/LinkedIn.php

i was getting this error

Catchable fatal error: Method Happyr\LinkedIn\AccessToken::__toString() must
return a string value  

i followed issues61. and fixed the error

  

if you could update the library for future use it will be helpfull to other
who are facing similar problem

the lines are as follow.

  public function getAccessToken()  
   {  
       if ($this-&gt;accessToken === null) {  
           if (null !== $newAccessToken = $this-&gt;getAuthenticator()-&gt;fetchNewAccessToken($this-&gt;getUrlGenerator())) {  
             /*  
               The following codes below fix the  
               Catchable fatal error: Method Happyr\LinkedIn\AccessToken::__toString() must return a string value  
               from issues61.  
               https://github.com/Happyr/LinkedIn-API-client/issues/61  
             */  
             $newAccessToken = unserialize ( serialize ( $newAccessToken ) );  
             $newAccessToken = $newAccessToken-&gt;getToken();  
             $this-&gt;setAccessToken($newAccessToken);  
           }  
       }  
  
       // return the new access token or null if none found  
       return $this-&gt;accessToken;  
   }  

  

  

Thanks in advance!

![](https://link.nylas.com/open/f4ajh4q3g2xdc7z2atr5d14n/local-166f23ba-
fe8b?r=cmVwbHkrMDA2NDk4ZWQxMDc3YWVmNjk2OGJjODVkMTExMWM5MGJjZDhiNmFiYzQzMDg5YTljOTJjZjAwMDAwMDAxMTM4ZDI2Njg5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 30 2016, at 9:27 pm, Tobias Nyholm &lt;notifications@github.com&gt;
wrote:  

> If you are using the SessionStorage you may do:

>  
>  
>     $session = new SessionStorage();

>     $session->clear('access_token');

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on GitHub](https://github.com/Happyr
/LinkedIn-API-
client/issues/107#issuecomment-229746891&r=cmVwbHkrMDA2NDk4ZWQxMDc3YWVmNjk2OGJjODVkMTExMWM5MGJjZDhiNmFiYzQzMDg5YTljOTJjZjAwMDAwMDAxMTM4ZDI2Njg5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the
thread](https://github.com/notifications/unsubscribe/AGSY7W0nVHxNHfBP63_WNWjHTJlgoFzdks5qRApogaJpZM4JCYVO&r=cmVwbHkrMDA2NDk4ZWQxMDc3YWVmNjk2OGJjODVkMTExMWM5MGJjZDhiNmFiYzQzMDg5YTljOTJjZjAwMDAwMDAxMTM4ZDI2Njg5MmExNjljZTA5YmE3ZjMwQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/AGSY7fOJVk3HT0_OBo8haLRgRaGzuPZYks5qRApogaJpZM4JCYVO.gif)
