### ISSUE TITLE
 I didn't find reading personal post 

### ISSUE THREAD

**Issue by qwe356558603** [Happyr/LinkedIn-API-client#110]
I can get the company's post but I don't get the people posts, I didn't find reading personal post use documents ,Or because I don't have enough permissions, I now only 4 a few basic permissions

**Comment by Nyholm** [comment]
This is an unofficial api client. Which means that I do not work at LinkedIn nor am I developing their API. 
I and many others using this client, are experts on how the client works, how to handle authentication and what data is stored where. For questions how to query the API you must turn to the LinkedIn documentation or contact their support.
