### ISSUE TITLE
Unable to use client with different Client IDs

### ISSUE THREAD

**Issue by marcelomg** [Happyr/LinkedIn-API-client#111]
First of all. Great app, thanks for sharing it.

I got it working, the only thing that I can't do (without opening a new browser on private window) is to use a different Client ID to post to another account.

I created an app from another LinkedIn user and try using different IDs but it always uses the same ID. I tried destroying the Session, but that doesn't work.

So if I want to create a loop and post to both accounts, that won't work. Is there a way I can make this work?

**Comment by Nyholm** [comment]
What if you use `LinkedIn::getAccessToken` and `LinkedIn::setAccessToken` to switch access tokens? That would make it possible for you to create a loop and post with both accounts, right?

**Comment by Nyholm** [comment]
@marcelomg did my suggestions help?

**Comment by Nyholm** [comment]
Im closing this due inactivity.
