### ISSUE TITLE
Unable to run the below code

### ISSUE THREAD

**Issue by rkkiiit** [Happyr/LinkedIn-API-client#112]
<?php
session_start();
use Happyr\LinkedIn\LinkedIn;
define('APP_ID', 'MY_ID'); 
define('APP_SECRET', 'MY_SECRET'); 
$linkedIn=new LinkedIn(APP_ID, APP_SECRET);
if ($linkedIn->isAuthenticated())
 {
    $user=$linkedIn->get('v1/people/~:(firstName,lastName)');
    echo "Welcome ".$user['firstName'];
     exit();
} //if authenticated
elseif ($linkedIn->hasError()) 
{
    echo "User canceled the login.";
    exit();
}
//if not authenticated
$loginUrl = $linkedIn->getLoginUrl();
echo "<a href='$loginUrl'>Login with LinkedIn</a>";
?>

**Comment by Nyholm** [comment]
What issues do you run in to? Are you using composer's autoload?

**Comment by rkkiiit** [comment]
the src file your team have uploaded doesn't content any autoload code.can i have an autoload php file?

**Comment by Nyholm** [comment]
You should be using composer. It will provide you an autoload file. Please read it's documentation. https://getcomposer.org/

**Comment by rkkiiit** [comment]
<?php

/**
 * Use to autoload needed classes without Composer.
 *
 * @param string $class The fully-qualified class name.
 * @return void
 */
spl_autoload_register(function ($class) {

    // project-specific namespace prefix
    $prefix = 'Happyr\\LinkedIn\\';

    // base directory for the namespace prefix
    $base_dir = __DIR__ . '/src/';

    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relative_class = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }
});

**Comment by rkkiiit** [comment]
is the above code will work??

**Comment by Nyholm** [comment]
It seams like you are not reading my comments. Please do the following: 

> You should be using composer. It will provide you an autoload file. Please read it's documentation. https://getcomposer.org/

**Comment by rkkiiit** [comment]
Ok thank you
