### ISSUE TITLE
Getting null data after authorizing the access

### ISSUE THREAD

**Issue by rkkiiit** [Happyr/LinkedIn-API-client#113]
After getting the authorization access of the user i am getting the null data.
The code is below:-

<?php
require __DIR__ . '/vendor/autoload.php';
define('APP_ID','xxxxxxxxxxx'); 
define('APP_SECRET','xxxxxxxxxxxx'); 
$linkedIn=new Happyr\LinkedIn\LinkedIn(APP_ID, APP_SECRET);
if ($linkedIn->isAuthenticated())
{
    
  
    $user=$linkedIn->get('v1/people/~:(firstName,lastName)');
    echo "Welcome ".$user['firstName'];

    exit();
} elseif ($linkedIn->hasError()) {
    echo "User cancelled the login.";
    exit();
}
$url = $linkedIn->getLoginUrl();
echo "<a href='$url'>Login with LinkedIn</a>";

?>

**Comment by Nyholm** [comment]
You must provide a more detailed error message if I should have a change to help you. 

* Where are you getting null data?
* What data did you expect?
* Do you feel that something is wrong with the client? If so, please provide a test

**Comment by rkkiiit** [comment]
after authozing the access $linkedIn->isAuthenticated() always returning false.
when i checked var_dump($linkedin) it is returning NULL.

**Comment by Nyholm** [comment]
`$linkedIn->isAuthenticated()` returns false because you are not authenticated properly. 

`var_dump($linkedin)` prints NULL because there is no variable named `$linkedin`. Looking at your code above you have a variable named `$linkedIn`. 

I will close this issue because you have not reported an error with the client.

**Comment by rkkiiit** [comment]
sorry its var_dump($linkedIn).
