### ISSUE TITLE
toString executed even if the response is empty

### ISSUE THREAD

**Issue by gestudio** [Happyr/LinkedIn-API-client#119]
| Q                       | A
| ----------------------- | ---
| Bug?                    | yes
| New Feature?            | no
| Are you using composer?  | yes
| Version                 | 7af5503b

#### Actual Behavior
If you refresh the redirect_url, where the isAuthenticated() function, you get an error.
When you refresh the redirect URL, the CFRS fails and so the linkedin response is empty.
This produces  an error when trying to convert to string a value expected to be in an object returned by linkedin in normal circunstances.

```
Warning (4096): Method Happyr\LinkedIn\AccessToken::__toString() must return a string value [ROOT/vendors/linkedin/src/LinkedIn.php, line 111]
Code Context
    {
        // Add access token to the headers
        $options['headers']['Authorization'] = sprintf('Bearer %s', (string) $this->getAccessToken());
$method = 'GET'
$resource = '/v1/people/~:(id,firstName,lastName)'
$options = array(
	'format' => 'json',
	'response_data_type' => 'array'
)
Happyr\LinkedIn\LinkedIn::api() - ROOT/vendors/linkedin/src/LinkedIn.php, line 111
Happyr\LinkedIn\LinkedIn::isAuthenticated() - ROOT/vendors/linkedin/src/LinkedIn.php, line 100
UsersController::linkedin() - APP/Controller/UsersController.php, line 346
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 118
```

#### Expected Behavior
If the response from Linkedin is empty, do not attempt to get a value from the response, just return false.

#### Steps to Reproduce

Once you are in the redirect_url with the data in the screen, refresh the page.

#### Possible Solutions

Do not execute Happyr\LinkedIn\AccessToken::__toString() if there is no access token or response provided by linkedin api.

**Comment by Nyholm** [comment]
Thank you for a detailed report. But I cant however reproduce this. 

If it is the first time you come to the redirect_url you have a `state` and a `code`. They are used to get an AccessToken that is saved in you storage. If you refresh the page you should get the access token directly form the storage. If the access token does not exist there (for some reason) we start to use the same `state` and `code` again. You **should** get a CFRS exception in that case. 

Can you debug these lines for me? In curious what happens after you refresh the page. How do you get your AccessToken? 
https://github.com/Happyr/LinkedIn-API-client/blob/7af5503b6ac28a0dca30eacdbb6c229af884611e/src/LinkedIn.php#L291-L299

**Comment by gestudio** [comment]
When you land the first time you have the state and code as you say.

If you refresh that same page (https://server.local/users/linkedin?code=AQSLes0CHzBL9mxjXgWJoi3oIYBTDiPGVl2FmZJvyyhGRE37aQbFVdf7YeWo7au1cF6k2G1PWcalyIC68PpKeDKwEJaF2yOHPiDTLqeAj_tsOtRPPnY&state=568276b1706e1696fa8a722f981fdcd7), instead of having a CFSR error, I get the pointed exception.

Not a big deal, I will just redirect the user to another page to avoid refresh.

How can I access the storage to get the token?

Thanks for the quick response!

**Comment by Nyholm** [comment]
You get the token by `$linkedIn->getAccessToken()`, no need to access the storage directly.

**Comment by Nyholm** [comment]
I assume that you solved this issue due the inactivity. If not, feel free to continue the discussion.
