### ISSUE TITLE
There is no extension able to load the configuration for "happyr_linkedin" (in /vagrant/app/config/config.yml). Looked for namespace "happyr_linkedin",

### ISSUE THREAD

**Issue by sterichards** [Happyr/LinkedIn-API-client#126]
| Q                       | A
| ----------------------- | ---
| Bug?                    | no|yes
| New Feature?            | no
| Are you using composer? | yes
| Version                 | Specific version or SHA of a commit

#### Actual Behavior

Error

#### Expected Behavior

Not to error :D

#### Steps to Reproduce

php app/console cache:clear

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by Nyholm** [comment]
It looks like you are running Symfony. Maybe try to install the bundle: https://github.com/Happyr/LinkedInBundle

**Comment by sterichards** [comment]
That doesn't seem to the case, as you can see my console out put here - http://pastebin.com/Bq46zwuB

If you have any ideas of why this may be happening, i'd be happy to hear them

**Comment by sterichards** [comment]
The problem was that I hadn't added:

`new \Happyr\LinkedInBundle\HappyrLinkedInBundle(),`

into AppKernel.php

It may be worth adding that into the documentation. As obvious as it seems to instantiate the bundle, sometimes peoples minds are too far elsewhere to do anything besides follow the documentation word for word without any room for improvisation :)

**Comment by Nyholm** [comment]
This is a PHP library. It has nothing todo with Symfony, Laravel, Zend, Wordpress or any other framework or CMS. What you have installed is the LinkedinBundle. That is another repo. See here: https://github.com/Happyr/LinkedInBundle

The installation documentation of the **bundle** does include the line you request. =)

**Comment by sterichards** [comment]
If i'm wrong here I shall look silly but I have to say that the bundle documentation doesn't include that line:

It only includes documentation to include the HttpplugBundle within appkernel.php:

`$bundles = array(
            // ...

            new Http\HttplugBundle\HttplugBundle(),
        );
`

**Comment by Nyholm** [comment]
Oh, yes. You are correct. It was only the HTTPlugBundle. 

See this PR: https://github.com/Happyr/LinkedInBundle/pull/6 
That would solve your issue.
