### ISSUE TITLE
PHP_Incomplete_Class_Object

### ISSUE THREAD

**Issue by gunnrryy** [Happyr/LinkedIn-API-client#130]
Hi,
I have installed this library using composer, and when i use/make call to LinkedIn API 1st time, it works perfect.
But theres some problem when calling isAuthenticated() method again from 2nd time ownwards.
tried to figure out, 
in isAuthenticated() method, getAccessToken() is internally called and is returning an PHP_Incomplete_Class_Object from Session.
because of which I am getting 500 Internal Server Error.

something that i noticed is, if i delete the cookie and try to hit API again, it works as if it is running for 1st time and i am getting desired result.

am I doing anything wrong?

my use case is, user log-in into my site using linked-in login, and after a few successful steps, i need to post a message on user's feed.

I am able to get the user logged in by calling the API 1st time,
but since the session is stored with PHP_Incomplete_object, when i try to post something to user's feed, I am calling isAuthenticated() again to check whether user is still logged in or no, if yes then post, else redirect to login get authenticated and then post.

i assume it is better to get checked whether user is logged in or no before trying to post.

the output of the accessToken is given below. please help

```
Happyr\LinkedIn\AccessToken Object
(
    [token:Happyr\LinkedIn\AccessToken:private] => __PHP_Incomplete_Class Object
        (
            [__PHP_Incomplete_Class_Name] => Happyr\LinkedIn\AccessToken
            [token:Happyr\LinkedIn\AccessToken:private] => AQUzD3LOESOCUc4QHCVEIAV1TbMompIPJUmxjh6QQj2coDQDpP42SLpMd5TpVud2wsdoq7FIBhF2tk201ZD48cLRKFBHIq-MMlze90JUKW7p0g6_QLRj3k_MRmqrEpGx2YHQgFMT-GVz_cqS3MBPea0kxyMG9ploiUu0mQPdJguw6h3_Sb8
            [expiresAt:Happyr\LinkedIn\AccessToken:private] => DateTime Object
                (
                    [date] => 2016-11-27 23:48:31.000000
                    [timezone_type] => 3
                    [timezone] => Asia/Kolkata
                )

        )

    [expiresAt:Happyr\LinkedIn\AccessToken:private] => 
)
```

how to solve this issue? or is there any other approach that i need to follow?
Thanks.

**Comment by gunnrryy** [comment]
hi @Nyholm 
i tried to debug the issue and LinkedIn class, 
adding unserialize(serialize($accessToken)) solved it for me

original 
```
public function getAccessToken()
    {
        if ($this->accessToken === null) {
            if (null !== $newAccessToken = $this->getAuthenticator()->fetchNewAccessToken($this->getUrlGenerator())) {
                $this->setAccessToken($newAccessToken);
            }
        }
        // return the new access token or null if none found
        return $this->accessToken;
    }
```

updated 
```
public function getAccessToken()
    {
        if ($this->accessToken === null) {
            if (null !== $newAccessToken = $this->getAuthenticator()->fetchNewAccessToken($this->getUrlGenerator())) {
                // added next line to solve the PHP_Incomplete_Class_Object issue
                $newAccessToken = unserialize(serialize($newAccessToken));
                $this->setAccessToken($newAccessToken);
            }
        }
        // return the new access token or null if none found
        return $this->accessToken;
    }
```

can you check and and if it is right could you please add it up?
so all can have this issue solved on next composer update for this repo.

thanks

**Comment by Nyholm** [comment]
Why would you serialize and then unserialize the access token?

**Comment by gunnrryy** [comment]
while storing the accessToken in session, there seems to be some issue. i could track it down till setAccessToken($accessToken) {
when i echo $_SESSION after setting it, it shows me the PHP_Incomplete_class_object and due to which i get 500 Internal server error.

**Comment by gunnrryy** [comment]
did the scenario reproduce at your tests?

**Comment by Nyholm** [comment]
I'm afraid not.
Can you make a PR with a failing unit test for this issue?

**Comment by gunnrryy** [comment]
unfortunately, have never used any unit testing.. will figure out how to unit test and get back to it soon.
(a bit new to all this)

**Comment by yash-khuthia** [comment]
Just a feed back on the issue. Just identified that we are storing session in redis, and when we try to store object in redis, its not stored properly and issue of PHP_INCOMPLETE_CLASS arises, 

tried same thing on regular session_handler, worked fine. so the issue is with storing object in redis.
