### ISSUE TITLE
Could not run composer require happyr/linkedin-api-client

### ISSUE THREAD

**Issue by voxuanthinh** [Happyr/LinkedIn-API-client#131]
| Q                       | A
| ----------------------- | ---
| Bug?                    | yes

#### Expected Behavior

What is the behavior you expect?

#### Steps to Reproduce
composer require happyr/linkedin-api-client

```
Problem 1
    - Installation request for happyr/linkedin-api-client 1.0.0 -> satisfiable by happyr/linkedin-api-client[1.0.0].
    - happyr/linkedin-api-client 1.0.0 requires php-http/client-implementation ^1.0 -> no matching package found.
```

#### Possible Solutions

If you have already ideas how to solve the issue, add them here.
(remove this section if not needed)

**Comment by Nyholm** [comment]
Hey. Thank you for this issue. 

Yes, this is the expected behavior. =) 
See the [installation instructions](https://github.com/Happyr/LinkedIn-API-client#installation) to find out why.
