### ISSUE TITLE
How to post image on linkedin profile

### ISSUE THREAD

**Issue by alibehroozi** [Happyr/LinkedIn-API-client#138]
Hello

I used your code to post a text on my profile
But the problem is how can I post an image ?
I couldn't do that.
Please Help Me.

Thanks

**Comment by Nyholm** [comment]
How come you cannot post an image?

**Comment by Nyholm** [comment]
Closing due inactivity.

**Comment by alibehroozi** [comment]
The picture will post on wall as a preview link not an image

**Comment by abdulbaquee** [comment]
Creating a rich media share is done in two steps. First, the media is uploaded to LinkedIn's media platform. Then, a personal or organization share referencing that media is created.

This URL might be help you.
[Rich Media share documentation link](https://developer.linkedin.com/docs/guide/v2/shares/rich-media-shares#upload)
