### ISSUE TITLE
getting  error url generator 

### ISSUE THREAD

**Issue by syedahnb** [Happyr/LinkedIn-API-client#14]
Fatal error: Class 'HappyR\LinkedIn\Http\UrlGenerator' not found in F:\xampp\htdocs\test9\HappyR\LinkedIn\LinkedIn.php on line 110
i using it in core php ,why i am facing this problem,or i calling wrong in php so help me how call in core php

**Comment by abdel07** [comment]
hi Nyholm,
is that in the new class added(branch master [Authenticator.php etc. ...]) you can update a token because I own a lifetime 60mn this token .
 thank you for your help
