### ISSUE TITLE
Without composer

### ISSUE THREAD

**Issue by reynan1996** [Happyr/LinkedIn-API-client#141]
| Q                       | A
| ----------------------- | ---
| Bug?                    | no|yes
| New Feature?            | no|yes
| Are you using composer? | no|yes

I am not using composer, how can i run this?

**Comment by Nyholm** [comment]
You can not. Composer is 6 years old now and the greatest thing that happen to PHP since MySQL support. You should use it, always. 

https://getcomposer.org/doc/00-intro.md
