### ISSUE TITLE
get Access Token issue

### ISSUE THREAD

**Issue by Chathula** [Happyr/LinkedIn-API-client#142]
| Q                       | A
| ----------------------- | ---
| Bug?                    | no
| New Feature?            | no
| Are you using composer? | yes
| Version                 | no

#### Actual Behavior

What is the actual behavior?
i tried to get access token using retrieved code. but i couldn't get it. this is what i got.

```json
{
"error": "invalid_request",
"error_description": "Unable to retrieve access token: appid or redirect uri does not match authorization code or authorization code expired"
}
```

#### Expected Behavior

What is the behavior you expect?
i expected to get the access token of authenticated user.

#### Steps to Reproduce

i used axios also, and tried using browser and php guzzle and postman. i got the same error.

axios

```javascript
  axios.post('https://www.linkedin.com/oauth/v2/accessToken', querystring.stringify({
          'grant_type'  : 'authorization_code',
          'code' : this.props.code,
          'redirect_uri' : 'http://localhost:3000/callback?network=linkedin',
          'client_id' : '869t0gxl7pc2uk',
          'client_secret' : 'YwIICg7ccOuo9ZcO'
        })).then(response => {
          console.log(response)
        })
```

php
```php
    $client = new GuzzleHttp\Client();
    $res = $client->requestAsync('POST', 'https://www.linkedin.com/oauth/v2/accessToken', [
      'form_params' => [
        'grant_type'    => 'authorization_code',
        'code'          => $request->input('code'),
        'redirect_uri'  => 'http://localhost:3000/callback?network=linkedin',
        'client_id'     => env('LINKEDIN_APP_ID'),
        'client_secret' => env('LINKEDIN_APP_SECRET')
      ]
    ]);
```

this is my linkedin developer dashboard details.

![Image of Linkedin Dashboard](http://i.imgur.com/bUiBkKo.png)
#### Possible Solutions

No idea...

**Comment by Chathula** [comment]
Ok just fixed the issue.. i have used code once it it expired. and also in client side there was a additional param form redirect_uri.

**Comment by ghost** [comment]
are you fixed this problem i have the same

**Comment by fureszk** [comment]
For me the solution was understanding that the authorization code is single use only. Thank you @Chathula for coming back and commenting what you've fined out, it helped me big time!
