### ISSUE TITLE
How to post an image

### ISSUE THREAD

**Issue by alibehroozi** [Happyr/LinkedIn-API-client#143]
Hello

How can I post my picture to my linkedin wall with this API ?
I use 'submitted-image-url' But it does not work properly

Thanks

**Comment by Nyholm** [comment]
Hello
What does the LinkedIn docs say?

**Comment by alibehroozi** [comment]
Linkedin Docs does not say much info about image
I want to know that Have you ever tried this API to post a image ?

**Comment by Nyholm** [comment]
I have not tried it, no. Looking at the [docs](https://developer.linkedin.com/docs/share-on-linkedin) and it seams pretty straight forward, doesn't it?

```json
{
  "comment": "Check out developer.linkedin.com!",
  "content": {
    "title": "LinkedIn Developers Resources",
    "description": "Leverage LinkedIn's APIs to maximize engagement",
    "submitted-url": "https://developer.linkedin.com",  
    "submitted-image-url": "https://example.com/logo.png"
  },
  "visibility": {
    "code": "anyone"
  }  
}
```

Im not sure why you run into issue, but it is not related to the client.

**Comment by alibehroozi** [comment]
Yes I use this code and it will post image but the image is just a link and just is a preview of that image.
The image is not complete ( cropped ) and you should click on that link ( https://example.com/logo.png ) to see full image on that place.
If you can, Please use this API to post an image then you'll see the issue.

**Comment by Nyholm** [comment]
Im not sure to be honest. Talk to LinkedIn support. 

Im closing this because it is not client related.

**Comment by alibehroozi** [comment]
Where is linkedin support ?

**Comment by Nyholm** [comment]
https://developer.linkedin.com/support

**Comment by alibehroozi** [comment]
You mean I should ask this question on stackoverflow ? because linkedin does not have support for development on their site

**Comment by Nyholm** [comment]
Yeah, wherever. I cannot give you support for LinkedIn API. In the same way that you cannot give me support on Googles APIs. (We have nothing todo with them). If LinkedIn recommends you Stackoverflow, then sure. Use it =)

I can, however, do my best in giving you support on this open source linkedin api **client**, but your issue is not related to the client.
