### ISSUE TITLE
Simplest way to just get a count of group members?

### ISSUE THREAD

**Issue by FrankEBailey** [Happyr/LinkedIn-API-client#146]
| Q                       | A
| ----------------------- | ---
| Bug?                    | no
| New Feature?            | no
| Are you using composer? | yes
| Version                 | Latest

#### Actual Behavior

I hate having to put a question as a dev issue but there doesn't seem to be any other venue for this. I would like some guidance in terms of the simplest possible way to authorise against the LinkedIn api in this client, and get the count of group members for a particular group. It seems like a lot of hoops to jump through just to get one single number. I'd scrape the group member total off the group page if LinkedIn didn't completely obfuscate their code to unlogged-in users.

**Comment by Nyholm** [comment]
Im not familiar with the specifics in the API. This client is just to handle authentication. See example on startpage.

I also know that the linkedin docs is not the best... I also know that some endpoints are for premium users only. Try asking on stackoverflow.

**Comment by FrankEBailey** [comment]
Thanks, I'll do so.
