### ISSUE TITLE
CurlException

### ISSUE THREAD

**Issue by rizaozden** [Happyr/LinkedIn-API-client#15]
Hi,

I'm getting this error while accessing access token, I explored code and found this issue:
SSL certificate problem: unable to get local issuer certificate

I tried  CURLOPT_SSL_VERIFYHOST => false, but error is still the same.

Thanks,
Riza

**Comment by Nyholm** [comment]
I've not pushed Version 0.3.0. It is using Guzzle. Extend LinkedIn::init and the GuzzleRequest class to easy modify the request.
