### ISSUE TITLE
Fatal error: Class 'Happyr\LinkedIn\LinkedIn' not found 

### ISSUE THREAD

**Issue by pratika2395** [Happyr/LinkedIn-API-client#156]
| Q                       | A
| ----------------------- | ---
| Bug?                    | no
| New Feature?            | no
| Are you using composer? |yes
| Version                 | 1.6.3

#### Actual Behavior
I'm doing a project in core php. I am using Happyr LinkedIn api client. When i try to use the commands -"
composer require php-http/guzzle6-adapter" and the rest of the commands mentioned in the procedure..I am getting "No command 'composer' found, did you mean:
 Command 'compose' from package 'mime-support' (main)
composer: command not found " in the terminal. 

#### Expected Behavior
The api to work as mentioned

#### Steps to Reproduce

No idea

#### Possible Solutions
To make those commands to work. But i don't know why i am unable to run in my terminal

**Comment by Nyholm** [comment]
You need to use Composer: https://getcomposer.org/

Im closing this since it is not an issue with the library. Please refer to places like Stackoverflow if you have questions about PHP.
