### ISSUE TITLE
Not getting response on https://www.linkedin.com/uas/oauth2/accessToken

### ISSUE THREAD

**Issue by snghaprv** [Happyr/LinkedIn-API-client#157]
getting following error

 About to connect() to www.linkedin.com port 443 (#0)
  Trying 103.20.94.1... connected
Connected to www.linkedin.com (103.20.94.1) port 443 (#0)
Initializing NSS with certpath: sql:/etc/pki/nssdb
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
 NSS error -5938
 Closing connection #0
 SSL connect error
curl: (35) SSL connect error

**Comment by Nyholm** [comment]
This is related to your machine and SSL. This is usually a problem with Windows. 

This library is decoupled from the HTTP client. I would recommend you to ask a question on StackOverflow.
