### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by ontelo** [Happyr/LinkedIn-API-client#16]
Hi,

There's something really weird going on. I don't know if this is temporal LinkedIn issue or something with this client.

Anyway I can't get AccessToken.

Application redirects nicely to LinkedIn authorization url and redirects back after approval, but then I get this message: Exception: Could not get access token.

I also tried with pure example code, but got the same results.

Anything to do with Poodle" SSL vulnerability? Even though I didn't find any traces of SSL being used.

Any thoughts?

**Comment by Nyholm** [comment]
Closing this due inactivity and because I fail to reproduce the issue. 

I have however improved the docs and the error messages.
