### ISSUE TITLE
How do I post to the linkedin wall?

### ISSUE THREAD

**Issue by iamjonathankush** [Happyr/LinkedIn-API-client#25]
How do I use the code to post a status update to the wall (the place where all the posts are on the homepage dashboard)?

**Comment by Nyholm** [comment]
What does the docs say? What do you have so far?

**Comment by Nyholm** [comment]
Hi @iamjonathankush 
How is it going with this issue? Did you manage to find out how you post on the wall?

**Comment by cithukyaw** [comment]
@iamjonathankush Here is how I'm trying to post on the wall

	$linkedInOAuth = new Happyr\LinkedIn\LinkedIn(LINKEDIN_APP_ID, LINKEDIN_APP_SECRET);

	if ($accessToken) { // assume that it is retrieved from session
		$linkedInOAuth->setAccessToken($accessToken);

		$postParams = array(
			'content' => array(
				'description' => 'I\'m so exciting to share a post using API.'
			),
			'visibility' => array(
				'code' => 'connnections-only'
			)
		);

		$result = $linkedInOAuth->api(
			'v1/people/~/shares',
			array(
				'format' => 'json'
			),
			'POST',
			$postParams
		);
	}

@Nyholm  I believe it is a correct procedure, however I got 400 bad request error:

> Fatal error: Uncaught GuzzleException: 400: Client error response [url] https://api.linkedin.com/v1/people/~/shares?format=json&oauth2_access_token=xxxxxxx [status code] 400 [reason phrase] Bad Request thrown in ...\vendor\happyr\linkedin-api-client\src\Happyr\LinkedIn\Http\GuzzleRequest.php on line 26

What could be the problem?

**Comment by cithukyaw** [comment]
[Share on LinkedIn API][1] requires the following two HTTP headers:

    Content-Type: application/json
    x-li-format: json

I was looking for how to set the additional header `x-li-format` in [`LinkedIn->api()`][4]. It may be missing there and in [GuzzleRequest.php][2] as they seems not accepting the header options in arguments. `$urlParams['format']` only is sent to [`GuzzleRequest->send()`][2].

I tested by temporarily adding the line `$options['headers']['x-li-format'] = 'json';` after [the line 55][3]. This did not resolve the issue though.

[1]: https://developer.linkedin.com/docs/share-on-linkedin
[2]: https://github.com/Happyr/LinkedIn-API-client/blob/master/src/Happyr/LinkedIn/Http/GuzzleRequest.php#L17
[3]: https://github.com/Happyr/LinkedIn-API-client/blob/master/src/Happyr/LinkedIn/Http/GuzzleRequest.php#L55
[4]: https://github.com/Happyr/LinkedIn-API-client/blob/master/src/Happyr/LinkedIn/LinkedIn.php#L145

**Comment by Nyholm** [comment]
I believe you have an error in your postParams array. It should read like this: 
```php
$postParams = array(
        "comment"=> "Check out developer.linkedin.com! http://linkd.in/1FC2PyG",
        'visibility' => array(
            'code' => 'connnections-only'
        )
    );
```
The url is needed. You can't just share your thoughts... You have to share a link as well. 
 However, this does not work since it looks like LinkedIn does not respect 2.5 in this [RFC
(http://www.ietf.org/rfc/rfc4627.txt). When you json_encode a url it will look like this: `{"myUrl":"http:\/\/example.com"}`
But LinkedIn will not recognize that as an valid URL. 

I'll see if I can do some rework on this.

**Comment by cithukyaw** [comment]
@Nyholm I copied the XML example and tested it. I got 500 internal server error. Please check my [SO question](http://stackoverflow.com/q/29934649/1179841).

**Comment by Nyholm** [comment]
Did you get a 500 response? Then it not much we can do. That's a problem on the LinkedIn servers. 

Like I said. I will see to find a fix for this. Give me until Thursday.

**Comment by Nyholm** [comment]
I've just merged new features and documentation into master. I believe it solves your problem. 

Check out the Upgrade.md and the new section in the Readme titled "Post on user's wall".

**Comment by cithukyaw** [comment]
Thank you. I will check and let you know.

**Comment by cithukyaw** [comment]
The version is 0.5.0? What version should I use when I use composer?

**Comment by Nyholm** [comment]
I have not tagged a version yet. Will probably to that within a couple of days. You should use 'dev-master'  as a version if you want to test the new features.

**Comment by cithukyaw** [comment]
I installed `dev-master`. Great, it works! Except I got error for xml post:

> Fatal error: Uncaught GuzzleException: 400: Couldn&#39;t parse Json body: Unexpected character (&#39;&lt;&#39; (code 60)): expected a valid value (number, String, array, object, &#39;true&#39;, &#39;false&#39; or &#39;null&#39;) at [Source: java.io.StringReader@e881cd7; line: 2, column: 7] thrown in \vendor\happyr\linkedin-api-client\src\Http\GuzzleRequest.php on line 34

**Comment by Nyholm** [comment]
> Except I got error for xml post:

Interesting error message. It does not really tell you what you are doing wrong... Anyhow: When you posting XML you need to make create the XML you self. You can not post an array like with json. See the example in the readme. 

> URL is required for the content option. The comment option does not require it though.

Thank you for that clarification.

**Comment by cithukyaw** [comment]
I followed your example. Here is my post param:

```
$postParams = array(
	"body" => "<share>
			<comment>PHPLucidFrame - The simple, lightweight and flexible web application development framework http://phplucidframe.sithukyaw.com</comment>
			<visibility>
				<code>anyone</code>
			</visibility>
		</share>"
);
$result = $linkedInOAuth->post('v1/people/~/shares', $postParams);
```

**Comment by Nyholm** [comment]
You are correct, The example is not good enough. I will rewrite it. 

It should be: 
```php
$postParams = array(
    "format"=>"xml",
    "body" => "<share>
            <comment>PHPLucidFrame - The simple, lightweight and flexible web application development framework http://phplucidframe.sithukyaw.com</comment>
            <visibility>
                <code>anyone</code>
            </visibility>
        </share>"
);
$result = $linkedInOAuth->post('v1/people/~/shares', $postParams);
```

Have a look on this section on formats: https://github.com/Happyr/LinkedIn-API-client#changing-format

**Comment by cithukyaw** [comment]
That's great and works!

**Comment by Nyholm** [comment]
Thank you for testing this. I will make sure to tag 0.5.0 tomorrow.

**Comment by Haiming717427** [comment]
Hi, Nyholm.
I download your source code and install it by composer.
as a result, vendor folder is created.
I changed the name 'happyr' to Happyr and 'linkedin-api-client' to 'LinkedIn'
and create a "index.php" to call it.
it's some code is
                       require_once 'autoload.php';
                        $linkedIn=new Happyr\LinkedIn\LinkedIn('756k6wdtntngffs','AtXwifuEIoff4xWvbb');
and copy index.php to vendor folder.
But When i test it, it occurs "Server 500 error".
I made something wrong when install it.
Please tell me the way.
thx.

**Comment by VirendraArekar** [comment]
Hoe to retrieve post from the user or app.Also how to comment it.

**Comment by VirendraArekar** [comment]
How to make hashtag and comment also.
