### ISSUE TITLE
Revoking tokens

### ISSUE THREAD

**Issue by HMAZonderland** [Happyr/LinkedIn-API-client#27]
Should tokens be removed at the client side only (from the database w/e) or from LinkedIn as well?

This Stackoverflow topic states it should be possible: http://stackoverflow.com/questions/11223357/how-to-remove-revoke-access-token-from-the-linkedin

But its from 2012.

**Comment by Nyholm** [comment]
Thank you for the link. I agree. You should remove the access token from your database if the user requests it. 

When you have authenticated your user you can get the token by calling `LinkedIn::getAccessToken()`. You may save it or throw it away. That is out of scope for the library.
