### ISSUE TITLE
Add documentation about how to integrate the library with Laravel

### ISSUE THREAD

**Issue by Nyholm** [Happyr/LinkedIn-API-client#31]
Like we got the Symfony2 documentation it would be nice to have a line or two and some code examples of how to use this library with Laravel.

Ping @andreascreten

**Comment by mauri870** [comment]
Hello Nyholm, I work in a new package for laravel, basically extends your class and use a syntax with an facade, much more simple for web artisans
[github.com/mauri870/laravel-linkedin](https://github.com/mauri870/laravel-linkedin)

**Comment by Nyholm** [comment]
Closed by https://github.com/Happyr/LinkedIn-API-client/pull/83
