### ISSUE TITLE
Unusable without the authentication procedure

### ISSUE THREAD

**Issue by appeltaert** [Happyr/LinkedIn-API-client#32]
Some people use oauth through other libraries. A user needs to be able to set an access token along with the app key and secret and be able to use it. I took a quick look but it doesn't seem to be possible.

The request class needs to set an additional header if so:

    Authorization: Bearer [access token]

JSON requests need the following header also:

    x-li-format: json

**Comment by Nyholm** [comment]
If you are using another way to get your access token (or you get one from your database storage) you may use `LinkedIn::setAccessToken`. You may also call the `LinkedIn::api` with an array that has a key named `oauth2_access_token` as second parameter. ([See code](https://github.com/Happyr/LinkedIn-API-client/blob/master/src/Happyr/LinkedIn/LinkedIn.php#L150))

### Additional headers
You can pass authentication token with a URL param. In fact, LinkedIn did just update their documentation suggesting to pass the authentication token as a header. 
That is something we should look into and update our `GuzzleRequest` class with.

**Comment by Nyholm** [comment]
I've done some updates lately. It is now way easier to specify headers and we are using the Authorization header. 
See #46.
