### ISSUE TITLE
Token expiration date

### ISSUE THREAD

**Issue by martins-pudelis** [Happyr/LinkedIn-API-client#33]
Would be great if there would be some way how to retrieve access token expiration date. 

At the moment as far as I see there isn't anything like that. I also cannot retrieve expires_in value from access token response.

**Comment by Nyholm** [comment]
Thank you. You are absolutely correct. What do you think about doing something like this: 
https://github.com/Happyr/LinkedIn-API-client/commit/c808d33bb22a6731f541f676da5a600e9c7553eb

**Comment by martins-pudelis** [comment]
That was quick!

To me, seems good solution.

**Comment by Nyholm** [comment]
Thank you. 

I'll write some tests evaluate it some more before I submit a PR.

**Comment by Nyholm** [comment]
Does the PR solve your problem. 

Any feedback or testing is appreciated.

**Comment by martins-pudelis** [comment]
Thanks! So far everything seems fine. If something will pop up will let you know.

When you are planning to release those improvements in Happyr/LinkedIn-API-client repository?

**Comment by Nyholm** [comment]
If you have tested it and you say everything is fine we can merge it as soon as I done some more testing.

**Comment by Nyholm** [comment]
Closed by #34

**Comment by Nyholm** [comment]
Pushed tag 0.4.0
