### ISSUE TITLE
Not able get past authorization

### ISSUE THREAD

**Issue by SandyRig** [Happyr/LinkedIn-API-client#35]
Hello,

I am using this on a WordPress project. I only want to get a specific company's updates.

I initially got facade fatal errors which I resolved using this.

"That is because you don't use the Facade. 
Remove the vendor folder and install it again with composer update --no-dev and you will use the global $_SESSION array."

Now I cant seem to get past this check
```if ($linkedIn->isAuthenticated()) {
    // my code
}```

I have double checked the App keys.

I am not sure why its not authenticating and I am not sure how to check for any errors. Any help or information would be highly appreciated. Thanks

**Comment by Nyholm** [comment]
Check out the latest code in the master. Do you still have issues?
Have you configured your application properly with redirect_uri etc?

**Comment by irfanevrens** [comment]
I am using this codes to pass isAuthenticated...
```
$_REQUEST['code'] = isset($_GET['code']) ? $_GET['code'] : null;
$_REQUEST['state'] = isset($_GET['state']) ? $_GET['state'] : null;

if ($linkedin->isAuthenticated()) {
```

**Comment by Nyholm** [comment]
Hey @irfanevrens 
I'm sorry I have not taken action on you answer until now. I've just made [a commit](https://github.com/Happyr/LinkedIn-API-client/commit/fcf0458494b9b06cd744fb9fa479b66a5d70cb48) that will solve this issue for you. 

It will be merged as soon as php-http is ready.
