### ISSUE TITLE
Unauthorized access to group messages

### ISSUE THREAD

**Issue by dtbaker** [Happyr/LinkedIn-API-client#36]
Hey,

Great API client! I'm struggling with authorization on group messages.

1) created a private group from http://www.linkedin.com/grp/ and posted some discussions as me
2) login with linkedin using this code:
```
$url = $linkedIn->getLoginUrl(array(
				'scope' => array(
					'r_basicprofile',
					'w_messages',
					'r_network',
					'w_share',
					'rw_groups',
				)
			));
```
3) access my group memberships (this works and correctly shows my newly created private group)
```
$api_result = $linkedIn->api('v1/people/~/group-memberships');
```
4) try to read the group messages from my private group:
```
$api_result = $linkedIn->api('v1/groups/'.$linkedin_group_id.'/posts?order=recency&category=discussion');
```
results in `Fatal error: Uncaught GuzzleException: 401: Client error response ....  [status code] 401 [reason phrase] Unauthorized  ... `

However I can correctly call this API endpoint through the test console and it shows my test messages, the URL and all that seems correct. https://apigee.com/console/linkedin 

Any ideas?

**Comment by dtbaker** [comment]
Ah never mind! I missed the $urlParams part of the api() method. This works fine

```
$api_result = $api->api('v1/people/~/group-memberships/'.$linkedin_group_id.'/posts' , array(
			'order' => 'recency',
			'role' => 'creator',
			'category' => 'discussion'
		));
```

**Comment by Nyholm** [comment]
Thank you for a very descriptive issue. I'm glad you solved it. I will start writing some documentation on this and on how to post messages. Do you have anything to contribute on that?

**Comment by dtbaker** [comment]
Yea when I figure it all out I'll post some example code

**Comment by Nyholm** [comment]
That would be great. Thank you!
