### ISSUE TITLE
Getting header data from API result

### ISSUE THREAD

**Issue by dtbaker** [Happyr/LinkedIn-API-client#37]
LinkedIn API returns some information in HTTP header fields after an API call.

For example, a POST to v1/groups/xyz/posts to create a "Group Message" will return a HTTP result like this:

HTTP/1.1 201 Created
X-LI-UUID: q0SEmZ0/0BOAZp3TbSsAAA==
Date: Mon, 30 Mar 2015 10:23:47 GMT
Vary: Accept-Encoding
Content-Length: 0
X-Li-Fabric: PROD-ELA4
 **Location: https://api.linkedin.com/v1/posts/g-8283043-S-5988253677960318977 **
x-li-request-id: ROT1ZIN59B
X-Li-Pop: prod-lva1
Connection: keep-alive
Server: Apache-Coyote/1.1

How can we get this "Location" information from the HTTP header of the result?

Thanks!

**Comment by dtbaker** [comment]
I changed the GuzzleRequest.php send() to this:

```public function send($url, $params = array(), $method = 'GET', $contentType = null, $return_header = null)```

and added this extra return value:

```
            if($return_header){
		    return (string) $response->getHeader($return_header);
	    }
```

I'm not sure of a way to do this without modifying GuzzleRequest.php?

then also change your Linkedin.php to this:

```
public function api($resource, array $urlParams=array(), $method='GET', $postParams=array(), $return_header = false)
```

and again in RequestInterface.php

```
public function send($url, $params = array(), $method = 'GET', $contentType = null, $return_header = false);
```

**Comment by Nyholm** [comment]
I did not know LinkedIn answered with information in the HTTP header. We should definutly support this. 

What you you think about adding a function like `LinkedIn::getLastHeaders`?

**Comment by dtbaker** [comment]
Yes adding something like that would be perfect.

**Comment by Nyholm** [comment]
Lets introduce a new method on the `RequestInterface`.

```php

/** 
 * @return array with HTTP headers. The header name is the array key. 
 */
public function getHeadersFromLastResponse();
```

To get headers from Guzzle is just doing `$response->getHeaders()`. To get headers from Curl you have to do some more work.. [Quick google](http://stackoverflow.com/questions/9183178/php-curl-retrieving-response-headers-and-body-in-a-single-request)

The GuzzleRequest and CurlRequest must have a instance variable that holds the header value. 

Does this seams like a good approach?

**Comment by Nyholm** [comment]
Have a look at the PR in #45. Does it work for you?

**Comment by dtbaker** [comment]
Great thanks!!
