### ISSUE TITLE
Cannot get access token

### ISSUE THREAD

**Issue by marcelonyc** [Happyr/LinkedIn-API-client#49]
Hi,

I am having trouble getting an access token. I tried debugging for a couple of days, but I can't trace the problem.

The URL gets constructed properly
/uas/oauth2/accessToken?grant_type=authorization_code&code=AQT9AFtORFRcPH58X_C0WAHhLgMOWFUPyl2M3fYMI7G7nKWwxmc9-Lbt2rV4B-M7xOaQBZ2VBz_MrreiiElVvqoLmQgtDKV1g5iq__2yvH_RIqgDjdU&redirect_uri=http%3A%2F%2Flocalhost%2Fwordpress%2Fafter-login%2F&client_id=<My Client>&client_secret=<My Secret>

I run the URL through a browser and I get an access token

{"access_token":"AQWf5EQwQnL6592nV3uxByR4aGNktwwndsi8RCapwKIzIf9VE09V01D5Ge3Cyzrfprd0W3PscL-ASQYCLj3bLC5lH4JW7gVfX0u3iA5caunlNhFkM9FZ0EIXHe0v4T-0qK7Rok0OUQvJte-l0uk7lhcVMjwD-vAFx9azyykDSxoyuBXyWsg","expires_in":5100784}

But when I run it inside my code it throws an exception 

Uncaught Exception: Could not get access token thrown in ...\LinkedIn-API-client-master\src\LinkedIn.php on line 374

Maybe you can point me in the right direction for debugging this.

Thank you

Marcelo

**Comment by Nyholm** [comment]
Try debug the `LinkedIn::getAccessTokenFromCode`. Where (in that function) does it fail?

**Comment by alexalouit** [comment]
Same here, getAccessToken() (call after getAccessTokenFromCode()) return only null value. I'm debugging to see where the problem is.

**Comment by Nyholm** [comment]
Thank you, please do.

**Comment by alexalouit** [comment]
It works now. See pull request #50.

**Comment by marcelonyc** [comment]
Thank you guys!

**Comment by Nyholm** [comment]
@marcelonyc Can you try this branch: https://github.com/Nyholm/LinkedIn-API-client/tree/serialize

Do you have the same problem now?

**Comment by marcelonyc** [comment]
Sorry is taking me so long to respond. I am having issues loading the class properly. It is my lack of composer knowledge not your api. I am not sure how to update the packages. When I run it, it can't find the class (LinkedIn) composer says there is nothing new to update/install. I was able to use it when I first did the composer install.

**Comment by marcelonyc** [comment]
You can ignore my previous comment. Off course, right after I sent you the message, I realized i modified the composer.json. Now I can invoke the class, but I am still having token issues. I am going to give it another try tomorrow and give you more info.

**Comment by Nyholm** [comment]
Any updates on this?

**Comment by marcelonyc** [comment]
I am still getting the error. 

"Fatal error: Uncaught Exception: Could not get access token thrown in ...\LinkedIn-API-client-serialize\src\LinkedIn.php on line 375"

**Comment by Nyholm** [comment]
Can you debug this?
Check `getAccessTokenFromCode`. What is happening? What data are you sending and what do you receive? The debug parameter to Guzzle might be helpful.

**Comment by marcelonyc** [comment]
Sorry it took so long to find this. The problem is that Guzzle did not accept my self-signed cert. To test I added this line to GuzzleRequest.php after line 32 ($client = $this->getClient();)

$client->setDefaultOption('verify', false);

With this option I get an access code correctly.

Thank you

Marcelo

**Comment by Nyholm** [comment]
This seams to be related to #53 

It could be solved by doing something like: 
```php 
$linkedin->get('/url', ['verify' => false]);
```
