### ISSUE TITLE
Does not work with Guzzle ~6.0

### ISSUE THREAD

**Issue by Modifikator** [Happyr/LinkedIn-API-client#57]
Are there plans to update the this library to work with the new version of guzzle? Thanks.

**Comment by Nyholm** [comment]
I've got no plans to do this in the near future. But a PR is welcome.

Implementing Guzzle6 should be easy. Just make a class that extends `Happyr\LinkedIn\Http\ RequestInterface`. I'm happy to review a PR and make sure Guzzle6 is the standard request class.

**Comment by sseshachala** [comment]
https://github.com/Happyr/LinkedIn-API-client/pull/58
Does this work?
