### ISSUE TITLE
Any way to run without composer?

### ISSUE THREAD

**Issue by dandyplow** [Happyr/LinkedIn-API-client#63]
Sorry to ask an idiotic question, but I can't get higher than php 5.3 on my server, so can't install via composer.  I am wanting to try out the LinkedIn api, having experience with Twitter and Facebook, both of which allow me to bypass composer installation by just doing a "require_once" of a file that exists in the library I download and then put on my server.  Any workaround to do this with yours?

Thanks in advance, I know this is a really basic issue, so I apologize for my ignorance!

**Comment by Nyholm** [comment]
First of all: make sure you update your php installation. It's a security issue. 
Then: composer requires 5,3,2+

If you can't or don't want to use composer you have to do the job. Download the source files and make sure to load the files.
