### ISSUE TITLE
Error: Invalid Acces token

### ISSUE THREAD

**Issue by nratifainah** [Happyr/LinkedIn-API-client#64]
Hello,
My application allow user to connect to linkedin (using javascript) and I store access token that I got from IN.ENV.auth.oauth_token. 
I would like to use this API to post to user's wall. 
I have followed the instruction, but I got Invalid acces token error.
Did I use correct acces token? Any idea how to fix this error? 

Thanks

**Comment by Nyholm** [comment]
Hey. 
I do not know how you got your access token from the javascript library. I'm not even sure if linkedIn allows you to use that access token with PHP. 

If you are using the `LinkedIn::setAccessToken` and you get a response saying "Invalid access token" there is not much the client (or any client) can do to help. Sorry. Try asking the LinkedIn engineers.
