### ISSUE TITLE
Post Content to a LinkedIn Page

### ISSUE THREAD

**Issue by nrileykc** [Happyr/LinkedIn-API-client#66]
How can I use your API to post content to a linked in page?  I have the user accept the permission rw_company_admin.  So how would I post an update to their company page?

**Comment by Nyholm** [comment]
You should read the official documentation here: https://developer.linkedin.com/core-concepts

You should also have a look at the documentation for the library: https://github.com/Happyr/LinkedIn-API-client#how-to-post-on-linkedin-wall

**Comment by milutinac** [comment]
@Nyholm When I post to [default company](https://developer.linkedin.com/docs/company-pages#testing) by changing `v1/people/~/shares` to `v1/companies/2414183/shares`, I'm getting `null` as a result, and post isn't published to company page.

What I'm missing?
