### ISSUE TITLE
Guzzle 

### ISSUE THREAD

**Issue by mzupek** [Happyr/LinkedIn-API-client#68]
How do I include guzzlehttp with this library? I keep getting 
Fatal error: Class 'GuzzleHttp\Client' not found in /home/jobminx/public_html/api/App/Happyr/Linkedin/Http/GuzzleRequest.php on line 89

I have put the GuzzleHttp folder in every folder on my site?

**Comment by Nyholm** [comment]
Are you using composer?

**Comment by mzupek** [comment]
I am not using composer.

**Comment by Nyholm** [comment]
Use composer and all your problems will be solved. https://getcomposer.org/

**Comment by mzupek** [comment]
Thanks...for nothing!
