### ISSUE TITLE
unable to get access code 

### ISSUE THREAD

**Issue by beeseenmedia** [Happyr/LinkedIn-API-client#69]
this is my code to fetch the code.

$linkedin = new LinkedIn(env('LINKEDIN_KEY'), env('LINKEDID_SECRET'));
$linkedin->getAccessToken();

i changed getAccessTokenFromCode() in order to debug so when it throws the exception it returns $e and here is what i get.

LinkedInApiException {#309 ▼
  #result: array:2 []
  #message: "missing required parameters, includes an invalid parameter value, parameter more than once. : client_secret"
  #code: 400
  #file: "*/vendor/happyr/linkedin-api-client/src/Http/GuzzleRequest.php"
  #line: 38
  -trace: array:53 []
}

any ideas on how to debug or fix this issue? is it this code or guzzle?

**Comment by Nyholm** [comment]
I think there is problem with your code.. Have you authenticated the user before you are running `$linkedin->getAccessToken();`?
See the examples in the readme.

**Comment by beeseenmedia** [comment]
i got it.  ID10T mistake.  that error can also be that the key or secret are missing/invalid.  i misspelled the LINKEDIN_SECRET. sorry about that, at least when that error comes up someone will know to check their app credentials.

thanks for taking the time to respond.
