### ISSUE TITLE
String could not be parsed as XML 

### ISSUE THREAD

**Issue by SelvaSurukam** [Happyr/LinkedIn-API-client#70]
Hi,

https://github.com/Happyr/LinkedIn-API-client/issues/49
like above mentioned sollution for issue, I tried adding this line $linkedIn->get('/url', ['verify' => false]);
 to your sample code i am getting issue like below
![linkedin](https://cloud.githubusercontent.com/assets/14159289/9712773/a20bc928-556a-11e5-8a05-204613e602bc.JPG)

my code will look like this,
<?php
require_once "vendor/autoload.php";

$linkedIn=new Happyr\LinkedIn\LinkedIn('xxxxxx', 'yyyyyyyyyy');
$linkedIn->get('/url', ['verify' => false]);
if ($linkedIn->isAuthenticated()) {
	
	//we know that the user is authenticated now. Start query the API
	$user=$linkedIn->get('v1/people/~:(firstName,lastName)');
	echo "Welcome ".$user['firstName'];
	exit();
} else if ($linkedIn->hasError()) {
	echo "User canceled the login.";
	exit();
}

//if not authenticated
$url = $linkedIn->getLoginUrl();
echo "<a href='$url'>Login with LinkedIn</a>";
?>

you can point me in the right direction for debugging this.

Thank you

Selva ganapathi

**Comment by Nyholm** [comment]
Are you having the same issue with version 0.7?

**Comment by Nyholm** [comment]
Closed because inactivity.
