### ISSUE TITLE
post on LinkedIn wall error 

### ISSUE THREAD

**Issue by nirmalthumber** [Happyr/LinkedIn-API-client#74]
I created a same function call like show in below example

     $linkedIn=new Happyr\LinkedIn\LinkedIn('app_id', 'app_secret');
      $linkedIn->setAccessToken('access_token_from_db');
      $options = array('json'=>
           array(
                  'comment' => 'Im testing Happyr LinkedIn client! https://github.com/Happyr/LinkedIn-API-client',
            'visibility' => array(
            'code' => 'anyone'
             )
          ) 
       );
       $result = $linkedIn->post('v1/people/~/shares', $options);
       var_dump($result);

But when i print response .. Getting null data . My application has w_share access . I also tried adding scope during authorization.

**Comment by Nyholm** [comment]
Are you having the same issue with version 0.7 of the library?

**Comment by Nyholm** [comment]
Closed because inactivity.
