### ISSUE TITLE
symfony2 Linkedin

### ISSUE THREAD

**Issue by gaet** [Happyr/LinkedIn-API-client#75]
Hello,

I try to use your bundle to post and get articles on the wall.
I use symfony2, and I make a service like your demo.

But I have a problem, when I try to authentificate and make a post the function isAuthentificated() is always at false.

This is my code:

Service:
    linkedin:
      class: WebSite\BackEndBundle\Services\LinkedInService
      arguments: ['fakeapi', 'fakesecret', 'r_basicprofile,r_emailaddress']

     Controller function:

     private function publicationLinkedIn($title,$description)
    {
        $linkedIn=$this->get('linkedin');
        
        if ($linkedIn->isAuthenticated()) {
            var_dump("authentification linkedin ok");
        }elseif ($linkedIn->hasError()) {
            echo "User canceled the login.";
            exit();
        }
        //var_dump($linkedIn);
        var_dump("fin publication linkedin");
    }

$linkedIn->isAuthenticated() return always false, $linkedIn->hasError() never return error, and if I make a fake path apiid or secret, I have no error too, like the condition does not exist.

Maybe I don't use correctly your bundle, but I don't see where.

Thanks you for your help.

PS: My service is correctly load because $linkedIn=$this->get('linkedin'); return an object with apiId,secret and more.

**Comment by Nyholm** [comment]
Hey.
First you need to make sure to authenticate a user to receive an AccessToken. You should store that in the database (or something). Whenever you need to post on the wall you need to call `$linkedin->setAccessToken($dbToken);`. After that call you will be authenticated and are free to post.

**Comment by gaet** [comment]
For the token, I understand, I need to be authentificated.

But  $linkedIn=$this->get('linkedin'); does not automatically authenticate ?
In your example, I see "This demonstrates how to authenticate with LinkedIn and send api requests" and the first step before test connection is the contructor.

 So, I had think the constructor connect to the api with apiId and secret.

Have I wrong?

**Comment by Nyholm** [comment]
I guess you have misunderstood it a little. I should make this page more clear. https://github.com/Happyr/LinkedIn-API-client/blob/master/docs/symfony.md

The code sample you are referring to checks if we are authenticated or not. If not, provide a link for the user to do the authentication progress. After the process you need to make sure to store the access token and you need to make sure to give the LinkedIn service the correct access token when you want to be authenticated.

**Comment by Nyholm** [comment]
See #76

**Comment by gaet** [comment]
Ok I see. But I have other question.

I need not redirect web page. So to make this, I use JS API of linkedin and when I'm connect with popup, I have the "oauth token".

Do you think with this oauth token, it's possible to use your bundle to post in PHP?

I try to make a $linkedIn->setAccessToken("my_oauth_token_js"), but I get an cURL error 60.
So, maybe it's not the same token between js and php?

I make this because I create a form to make news of a website, and I would like possibility to make options (checkbox) to post automaticaly on social network (like linkedin, facebook, etc).

**Comment by Nyholm** [comment]
Okey. That is a great feature. I do not know if you can use a is token. Please try and come back to me with the answer. :)

I looked in to your error. The [documentation](http://curl.haxx.se/libcurl/c/libcurl-errors.html) says that it an error verifying the ssl certificate. 

CURLE_SSL_CACERT (60)

Peer certificate cannot be authenticated with known CA certificates.


I believe you could do something like this on the client to test if it works. 

$client->setDefaultOption('verify', false);

**Comment by gaet** [comment]
So, I have try.

$client->setDefaultOption('verify', false); resolved the ssl problem .

But I obtain an other error: Invalid acces token.  
So I think it's not possible, or the "auth token" isn't the "acces token".

I will make others tests.

**Comment by Nyholm** [comment]
Okey. Interesting. Thank you for keeping me posted.

**Comment by gaet** [comment]
It's work!

I have install php_oauth.dll on my xampp
I have make step one and two of this tuto to connect on js and give to the server the access token: https://developer-programs.linkedin.com/documents/exchange-jsapi-tokens-rest-api-oauth-tokens

This tutorial use cookie for get acces_token.

After use this method and get the cookie, I can use your bundle to get or post on the wall, without redirection for the login.


But I don't undestand, I don't need to make $linkedin->setAccessToken($acces_token);. If make this, I have always "bad acces token".

I don't think is the best solution, but it's the beginning.
