### ISSUE TITLE
scopes as consts?

### ISSUE THREAD

**Issue by Lewiscowles1986** [Happyr/LinkedIn-API-client#78]
Would it be a good idea to have the scope's as library constants as opposed to strings?

**Comment by Nyholm** [comment]
hm. That is an interesting idea. Could you please elaborate a bit on it? What are the pros and cons?

**Comment by Lewiscowles1986** [comment]
The pro's are that if the library needs to expand, or changes to the scope's are actioned, then there is one central place to update the strings, rather than having them dotted around your code

to give an example, of something I use with BigCommerce PHP library (it's an awful API, try to avoid)

```PHP
//... use statements etc
class bigcommerceAPI {
    const ORDER_STATUS_INCOMPLETE = 0;
    const ORDER_STATUS_PENDING = 1;
    const ORDER_STATUS_SHIPPED = 2;
    const ORDER_STATUS_PARTSHIPPED = 3;
    const ORDER_STATUS_REFUNDED = 4;
    const ORDER_STATUS_CANCELLED = 5;
    const ORDER_STATUS_DECLINED = 6;
    const ORDER_STATUS_AWAITING_PAYMENT = 7;
    const ORDER_STATUS_AWAITING_PICKUP = 8;
    const ORDER_STATUS_AWAITING_SHIPMENT = 9;
    const ORDER_STATUS_COMPLETED = 10;
    const ORDER_STATUS_AWAITING_FULFILLMENT = 11;
    const ORDER_STATUS_MANUAL_VERIFY_REQ = 12;
//... rest of helper library
```

This means that in the projects I use this in, I can update my helper library, and know that rather than type the number, which seems confusing and arbitrary, I can do things like the following

```php
$stauses = [
    bigcommerceAPI::ORDER_STATUS_AWAITING_FULFILLMENT,
    bigcommerceAPI::ORDER_STATUS_AWAITING_SHIPMENT
];
foreach($statuses as $status) {
```

or

```php
switch ($order->status_id) {
	case bigcommerceAPI::ORDER_STATUS_AWAITING_FULFILLMENT:
		// Send to ERP...
		break;
	case bigcommerceAPI::ORDER_STATUS_AWAITING_SHIPMENT:
		// Check for updates from ERP...
		break;
}
```

Maybe it's just me, but I think that is a lot more readable than with the numbers. Of course there are situations where helpers should be part of a separate class to helper wrapper etc, which I don't want to get held up with.

**Comment by Nyholm** [comment]
I see you point of not dealing with integers.

The scopes are only used in `LinkedIn::getLoginUrl`. I do not see the point of using constants in this case to be honest. 
```php

// Now
$url = $linkedin->getLoginUrl(['scope'=>'r_fullprofile,r_emailaddress,w_share']);

// With constants
$url = $linkedin->getLoginUrl(['scope'=>[LinkedIn::SCOPE_FULLPROFILE, LinkedIn::SCOPE_EMAIL_ADDRESS, LinkedIn::SCOPE_SHARE]]);
```

**Comment by Lewiscowles1986** [comment]
It's fine, just a note, the code I provided was hella-old, from early 2013 I think, so to update it would be probably using 

```php
// use relevant classes
use \Happyr\LinkedIn\Api;

// ...

// Use the code elsewhere
$cli->getLoginUrl([
    'scope'=>[
        Api::READ_FULLPROFILE,
        Api::READ_EMAIL,
        Api::SCOPE_SHARE
    ]
]);
```

It's only a small difference, but I think it makes it much more readable. It's probably just me, I can be opinionated over minutia at times; so it's no biggie

**Comment by Nyholm** [comment]
Unless for readability I see no benefit. It just adds some more coupling to LinkedIn. If they add/remove scopes we have to add/remove constants. 

And how much more readable is it really?

```
$cli->getLoginUrl([
    'scope'=>[
        'r_fullprofile',
        'r_emailaddress',
        'w_share'
    ]
]);
```

**Comment by Lewiscowles1986** [comment]
again, not arguing, but it's pretty coupled to linkedin as a linkedin api lib? 

Have a great weekend buddy :+1:

**Comment by Nyholm** [comment]
Hehe. Yeah. I know it sounds ironic. 
But I believe LinkedIn may do what ever changes they want to the API without any updates are required to the API client. 

Today that is true for everything but authentication process. 

But thank you for challenging this topic. 

Have a nice weekend.
