### ISSUE TITLE
Move to guzzle v6?

### ISSUE THREAD

**Issue by dusterio** [Happyr/LinkedIn-API-client#79]
At the moment this package is tied to guzzle ~5.0, so you cannot install it if you have, let's say, guzzle 6 (Laravel out of box got it)

Would be useful to migrate to newer guzzle, rather than forcing people to fork :)

**Comment by Nyholm** [comment]
Have a look at #73. It is on it's way. We are just waiting on [PHP-HTTP](http://docs.httplug.io/en/latest/) to become stable.

**Comment by nWidart** [comment]
Hello,

Are there any news about this ?

Thanks

**Comment by Nyholm** [comment]
Yes, PHP-HTTP (organization) is planning on making Httplug stable before the end of the year. I updated #73 just a few days ago with the latest changes in Httplug. 

If you want to help, download that fork and try it out.

**Comment by nWidart** [comment]
Alright, I'll set me on the PSR7 branch and see how it goes.

Thanks.

**Comment by Nyholm** [comment]
You might need to add the following to your composer.json because they have not tagged versions over at php-http yet. 

```yaml
"require": {
   "php-http/guzzle6-adapter": "dev-master",
   "php-http/httplug": "dev-master",
   . . . 
}
```

**Comment by nWidart** [comment]
Indeed, had to have the following:

``` json
"happyr/linkedin-api-client": "dev-psr7",
"php-http/guzzle6-adapter": "^0.2.0@dev"
```

**Comment by Nyholm** [comment]
php-http/httplug is now in beta. I've merged our PSR-7 branch to master now.

**Comment by nWidart** [comment]
Okay thanks, I'll try it out on Monday and see how it goes.
