### ISSUE TITLE
Guzzle v6, client error 403 on valid request

### ISSUE THREAD

**Issue by nWidart** [Happyr/LinkedIn-API-client#80]
Hello,

I'm using the `psr7` feature branch using Guzzle6.
I'm having issues running the following request:

``` php
$this->linkedIn->get('v1/companies', ['format' => 'json', 'query' => ['is-company-admin' => 'true']]);
// Same with:
$this->linkedIn->get('v1/companies', ['query' => ['is-company-admin' => 'true', 'format' => 'json',]]);
```

Which is returning a `Client error: 403`. Although when checking the built URL I have:

```
https://api.linkedin.com/v1/companies?is-company-admin=true&format=json
```

Which is working on [apigee](https://apigee.com/console/linkedin?req=%7B%22resource%22%3A%22%2Fpeople%2F~%3Fformat%3Djson-get%22%2C%22params%22%3A%7B%22query%22%3A%7B%22format%22%3A%22json%22%2C%22parameters_name_0%22%3A%22is-company-admin%22%2C%22parameters_value_0%22%3A%22true%22%2C%22parameters_name_1%22%3A%22format%22%2C%22parameters_value_1%22%3A%22json-get%22%2C%22parameters_name_2%22%3A%22format%22%2C%22parameters_value_2%22%3A%22json-get%22%7D%2C%22template%22%3A%7B%7D%2C%22headers%22%3A%7B%7D%2C%22body%22%3A%7B%22attachmentFormat%22%3A%22mime%22%2C%22attachmentContentDisposition%22%3A%22form-data%22%7D%7D%2C%22verb%22%3A%22get%22%7D), with the exact same URL.

Am I missing something ? 

Thank you,

**Comment by Haiming717427** [comment]
Hi, nWidart.
I download your source code and install it by composer.
as a result, vendor folder is created.
I changed the name 'happyr' to Happyr and 'linkedin-api-client' to 'LinkedIn'
and create a "index.php" to call it.
it's some code is
require_once 'autoload.php';
$linkedIn=new Happyr\LinkedIn\LinkedIn('756k6wdtntngffs','AtXwifuEIoff4xWvbb');
and copy index.php to vendor folder.
But When i test it, it occurs "Server 500 error".
I made something wrong when install it.
Please tell me the way.
thx.

**Comment by nWidart** [comment]
Hello,

Any updates on this by any chance ?

Thank you

**Comment by Nyholm** [comment]
Hey. The Httplug is about to be stable at any day now. I'm waiting on their changes. 

Thank you for taking the time testing this.

**Comment by Nyholm** [comment]
I've debugged this. I cant reproduce the error. Are you sure that you have the correct scope? 

Try to use this when you authenticate the user: 
```php
$linkedIn->getLoginUrl(['scope'=>'w_share']);
```

**Comment by nWidart** [comment]
Hm I have that scope configured in my linkedin app. I'll have to try with specifying it in loginurl

![screen shot 2016-01-04 at 10 52 32](https://cloud.githubusercontent.com/assets/882397/12087201/575ff146-b2d1-11e5-9fa3-9c50031f553f.png)

Currently, on version `0.6.3`, when running the above command, I'm getting:

``` php
$this->linkedIn->get('v1/companies', ['format' => 'json', 'query' => ['is-company-admin' => 'true']]);
```
 [RuntimeException]             
  Puli Factory is not available 
```

**Comment by Nyholm** [comment]
I saw that you opened an issue on php-http/discovery and that they included puli/cli as a dependency. 

I just updated the master (https://github.com/Happyr/LinkedIn-API-client/commit/c291cbe302c2dc0bfcc74d7c22cbd6920941a8b7) so now you may require the lastest from php-http/discovery

**Comment by nWidart** [comment]
Thank you.

Quick update, I started working on this feature again, and now making the same api call (`v1/companies`), returns the following:

![screen shot 2016-01-06 at 14 31 04](https://cloud.githubusercontent.com/assets/882397/12143660/e316df6c-b482-11e5-8492-f883842b6e1b.png)

I am admin of one company on linkedin so not sure why I'm getting that.

**Comment by Nyholm** [comment]
Do you have the `rw_company_admin` permission?

Ref: https://developer.linkedin.com/docs/company-pages

**Comment by nWidart** [comment]
Via the screenshot posted here , https://github.com/Happyr/LinkedIn-API-client/issues/80#issuecomment-168627370 , the linkedin app has all the boxes ticked, `rw_company_admin` too.  So I didn't think of adding it again to the method to get the login url.

However by explicitly adding it to the getLoginUrl method *as well*, it seems to work.

```
$loginUrl = $this->linkedIn->getLoginUrl(['redirect_uri' => route('connect.linkedin.callback'), 'scope' => 'w_share,rw_company_admin']);
```

Their documentation is pretty confusing regarding this. :astonished: 

Thank you for your time and great support!

**Comment by Nyholm** [comment]
Sorry, I saw that screenshot but I missed the `rw_company_admin`. 

> However by explicitly adding it to the getLoginUrl method as well, it seems to work.

That is weird. I think I've read somewhere that what you add on the api admin page is the defaults... 

> Their documentation is pretty confusing regarding this. 

Their documentation is way better now than 2 years ago when I started developing this client. 

Thank you for trying out the dev-master!

**Comment by nWidart** [comment]
Man, I'm scared to see their documentation from 2 years ago than :astonished:
