### ISSUE TITLE
Server 500 error

### ISSUE THREAD

**Issue by Haiming717427** [Happyr/LinkedIn-API-client#81]
Hi, Nyholm.
I download your source code and install it by composer.
as a result, vendor folder is created.
I changed the name 'happyr' to Happyr and 'linkedin-api-client' to 'LinkedIn'
and create a "index.php" to call it.
it's some code is
require_once 'autoload.php';
$linkedIn=new Happyr\LinkedIn\LinkedIn('756k6wdtntngffs','AtXwifuEIoff4xWvbb');
and copy index.php to vendor folder.
But When i test it, it occurs "Server 500 error".
I made something wrong when install it.
Please tell me the way.
thx.

**Comment by Nyholm** [comment]
Hey @Haiming717427. 
Welcome to Github. I see that you have published your question in 3 different places within just a few minutes. That is never a good idea. Once is enough. 

About your issue: I'm not too sure what you have changed but it no need changing anything. It will work if you just install it with composer and use the code example from the start page. 

For any future issue, please add a detailed error message. `Server 500 error` does not say much about the error.

**Comment by Haiming717427** [comment]
Sorry , Nyholm.
I found it was my fault.
I closed the issue.
I start

**Comment by Haiming717427** [comment]
Sorry, It was my fault.
I start programming about LinkedIn (post comment, upload photo).
I need your help.
How can i contact with you? 
Because i have questions about your code, i want to ask you.
Thx.

**Comment by Nyholm** [comment]
This is the way you can contact me. There is no benefit for the community if you and I talk in private. 

This library help you with the authentication process. How you do some API calls and what parameters to use is documented in the LinkedIn's developer page.

**Comment by Haiming717427** [comment]
Thank you for talking to me.
I am a beginner in LinkedIn and i don't have problem now.
This way isn't right because this issue must be closed. 
so, i can't talk with you anymore. 
Please tell me other way to talk with you.
Best regards.

**Comment by Nyholm** [comment]
> This way isn't right because this issue must be closed/private. 

I can not have a private discussion with you. There are hundreds of new users to this library every week. I don't have time to privately message them all. I'm sorry. If you have any issues, make sure to read the documentation that is provided by this library and Linkedin. If you still have a problem, open one issue on Github.

**Comment by Haiming717427** [comment]
Ok, I will follow your way.
I developed   a code  in Facebook PHP SDK V5(login and post comment/photo user timeline).
I have no experience in LinkedInApi,

While i running your 'LinkedIn login', i have this error:   invalid redirect_uri. This value must match a URL registered with the API Key."
I think i made something wrong about setting my App.
Please tell me about it.
Thank you.

**Comment by Nyholm** [comment]
Look in the Readme. The second paragraph gives you a link to LinkedIn that you have to read. 
Please read the documentation provided before you ask questions.

**Comment by Haiming717427** [comment]
Thanks. I will.

**Comment by Haiming717427** [comment]
Hi, Nyholm.
I logged in LinkedIn succssfully!I have a problem while running your 'post linked wall' code. I wrote code like below. 
session_start();
require_once 'autoload.php';
$linkedIn=new Happyr\LinkedIn\LinkedIn('756k6wdtntngfs','AtXwiuEIobR4xWvb');
if ($linkedIn->isAuthenticated()) {
    //we know that the user is authenticated now. Start query the API
    $user=$linkedIn->get('v1/people/~:(firstName,lastName)');
    echo "Welcome ".$user['firstName'];
    //Post comment
    $options = array('json' => array('comment' => 'Im testing LinkedIn client!'), 'visibility' => array('code' => 'anyone'));
    $result = $linkedIn->post('v1/people/~/shares', $options);
 
    var_dump($result);
        exit();
} elseif ($linkedIn->hasError()) {
    echo "User canceled the login.";
    exit();
}

//if not authenticated
$url = $linkedIn->getLoginUrl();
echo $url;
echo "<a href='$url'>Login with LinkedIn</a>";when running it, this error occurs
"The website encountered an error while retrievinghttp://128.199.199.195/LoginLinkedInSite/vendor/lk-login.php. It may be down for maintenance or configured incorrectly."
I saw docs in linkedIn but i can't find the solution.
Please guide me. Thank you.

**Comment by Nyholm** [comment]
You have added the `http://128.199.199.195/LoginLinkedInSite/vendor/lk-login.php` as redirect url, right? Somehow, you are redirecting to a remote server and I don't know why.

**Comment by Haiming717427** [comment]
Thanks for response.
Now, i am now employing by one project(hub staff-tracking project).
My task is login Facebook,LinkedIn,Tweeter,Pinterest,Instagram sites and post comment/photo to each site. This task must be finished until this week.
I am a beginner in web dev and php.
I do the task about Facebook and i read docs about  OAuth2 in linkedIn.
I am now trying to do about LinkedIn.
I must upload the result to another computer. 
So, i am redirecting to remote server and test on it.
I looked issue#25 and changed $option to
'json'=>array('comment'=>'Im testing Happyr LinkedIn client! https://github.com/Happyr/LinkedIn-API-client'),'visibility'=>array('code'=>'anyone'));
so, when running it there is no error occurs, but on "www.linkedin.com"\profile\your updates
there is no updates
I saw the readme.md file. I misunderstand about the paragraph below.
     You may of course do the same in xml. Use the following option array.
     $options=array('format'=>'xml', 'body'=>'<share>
     <comment> Im testing Happyr LinkedIn client! https://github.com/Happyr/LinkedIn-APi-client</comment>
    <visibility><code>anyone</code></visibility></share>');
Is this mean that i make xml file and copy this code in it?
Please tell me about it.
I don't have deep knowledge about php and web dev work. I am so beginner.
Please guide and help.
Thanks.

**Comment by Haiming717427** [comment]
Thanks for response.
I must upload the result to another computer. 
So, i am redirecting to remote server and test on it.
I looked issue#25 and changed $option to
'json'=>array('comment'=>'Im testing Happyr LinkedIn client! https://github.com/Happyr/LinkedIn-API-client'),'visibility'=>array('code'=>'anyone'));
so, when running it there is no error occurs, but on "www.linkedin.com"\profile\your updates
there is no updates
I saw the readme.md file. I can't understand about the paragraph below.
You may of course do the same in xml. Use the following option array.
$options=array('format'=>'xml', 'body'=>'
Im testing Happyr LinkedIn client! https://github.com/Happyr/LinkedIn-APi-client
anyone');
Does this mean that i make xml file and copy this code in it?
Please tell me about it.
I don't have deep knowledge about php and web dev work. I am so beginner.
Please guide and help.
Thanks. 


    On Friday, November 27, 2015 11:04 PM, Tobias Nyholm <notifications@github.com> wrote:
 

 You have added the `http://128.199.199.195/LoginLinkedInSite/vendor/lk-login.php` as redirect url, right? Somehow, you are redirecting to a remote server and I don't know why.
