### ISSUE TITLE
$linkedIn->isAuthenticated() always returning false

### ISSUE THREAD

**Issue by teol** [Happyr/LinkedIn-API-client#85]
Hello,

This is not about a "real" issue but I'm stuck with my problem, trying to make a LinkedIn Connect.
I did some LinkedIn connects but right now I don't know where my issue can be.

In the login process everything is going well, but at the end both $linkedIn->isAuthenticated() and $linkedIn->hasError() return false, because the access token might not be recognized.

The only difference I found with my other made LinkedIn Connects (using your lib) is that the urls are encoded so the GET parameters might not work well.

Here is a var_dump($_GET): 
```
array (size=1)
  'code=AAAZyVupt8xF-0-UCdC9-P-HAYaS54Mos7f71JQ-M-OKUlSk1j0KwQ7FRy0Nd0tzbl8lQ7-petcUWA4TrNZ_V9WssMOQEHUWkBXGi-Zz4aFpXJ9cywc&state=eabddd7452008ca50ead94a050a547786' => string '' (length=0)
```

So I tried to repopulate it correctly as it follows:
```
array (size=2)
  'code' => string 'AAAZyVupt8xF-0-UCdC9-P-HAYaS54Mos7f71JQ-M-OKUlSk1j0KwQ7FRy0Nd0tzbl8lQ7-petcUWA4TrNZ_V9WssMOQEHUWkBXGi-Zz4aFpXJ9cywc' (length=115)
  'state' => string 'eabddd7452008ca50ead94a050a547786' (length=32)
```

But $linkedIn->isAuthenticated() is still returning false :/ so it may not be related to the urls encoding.

Any idea how I could get it working?

Thanks

**Comment by Nyholm** [comment]
Do you have the same issue with the PSR7 branch?

**Comment by hailohailo** [comment]
Hey Nyholm, getting the same issue here. Is there anything that's changed in the package? Can't find the PSR7 branch to test

**Comment by Nyholm** [comment]
The PSR7 branch is now merged into master. There is a quite large change it the package between the latest stable version and master. You can see it here: https://github.com/Happyr/LinkedIn-API-client/pull/73

**Comment by hailohailo** [comment]
Perfect, thanks man. Appreciate that
