### ISSUE TITLE
Could not get access token

### ISSUE THREAD

**Issue by madhabkirank** [Happyr/LinkedIn-API-client#86]
Fatal error: Uncaught Exception: Could not get access token thrown in C:\xampp\htdocs\linkdin\vendor\happyr\linkedin-api-client\src\LinkedIn.php on line 374

**Comment by Nyholm** [comment]
Try with dev-master, do you get the same error?

**Comment by madhabkirank** [comment]
Thank You, Now it's working...............

On Fri, Jan 1, 2016 at 7:50 PM, Tobias Nyholm <notifications@github.com>
wrote:

> Try with dev-master, do you get the same error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Happyr/LinkedIn-API-client/issues/86#issuecomment-168309534>
> .
>



-- 
Regards,

*Nilamadhab Khanda*

*PHP Developer *
*iRankMedia.com*

**Comment by ketavc** [comment]
@Nyholm ,
I'm getting same error. 

> Could not get access token 
> 500 Internal Server Error - LinkedInApiException

I'm attaching Screen shot of Error page.
![selection_004](https://cloud.githubusercontent.com/assets/7146539/15388929/08233374-1dd2-11e6-8e5a-393feee80f34.png)
