### ISSUE TITLE
start-timestamp option doesn't look to be used

### ISSUE THREAD

**Issue by nWidart** [Happyr/LinkedIn-API-client#91]
Hello,

I'm trying to get the `Historical Status Update Statistics` data for a company page.

According to https://developer-programs.linkedin.com/historical-company-statistics#toggleview:id=json it needs a `start-timestamp` option.

This is my URI:

```
https://api.linkedin.com/v1/companies/[company_id]/historical-status-update-statistics:(like-count,impression-count,click-count,comment-count,share-count)?time-granularity=day&start-timestamp=1452073276
```
The `1452073276` is the timestamp from yesterday (`"2016-01-06 09:41:16.000000"` to be exact), and yet when I dump the returned data, the first one returned is from 2013.

Did I miss something (again) about this ?

I'm thinking linkedin *is* reading the option, since if I remove it, it returns the message saying it's required.

Edit: `1452073276` in milliseconds `1452073276000` provides the same result

**Comment by nWidart** [comment]
*(Sorry for the empty post at first. Pressed enter while in the title section)*

**Comment by nWidart** [comment]
Alright, silly me, had to do `timestamp *1000` for milliseconds.

My bad. :smile:

**Comment by Nyholm** [comment]
:smile:
