### ISSUE TITLE
Could not find a stored CSRF state token on use IlluminateSessionStorage

### ISSUE THREAD

**Issue by mauri870** [Happyr/LinkedIn-API-client#92]
Hi Nyholm, I get this error after set the storage class for use illuminate storage instead your default class. Any help for this issue? Thanks again

**Comment by Shandur** [comment]
@mauri870 How did you solve the problem?

**Comment by pratika2395** [comment]
@mauri870  did u solved this issue?

**Comment by mauri870** [comment]
Honestly,  I don't remember and I haven't used this library for a while now... You guys can check the laravel package to test out if this issue still happens.

https://github.com/artesaos/laravel-linkedin

**Comment by pratika2395** [comment]
@mauri870 okay. I wil try
