### ISSUE TITLE
Getting Error Message

### ISSUE THREAD

**Issue by mbarwick83** [Happyr/LinkedIn-API-client#93]
When I try installing this via composer/terminal, I get the following error. I'm using Laravel 5.1. Guzzle6.

`composer require happyr/linkedin-api-client:dev-master php-http/httplug:v1.0.0-beta`

```
  Problem 1
    - Installation request for happyr/linkedin-api-client dev-master -> satisfiable by happyr/linkedin-api-client[dev-master].
    - happyr/linkedin-api-client dev-master requires php-http/client-implementation 1.0 -> no matching package found.
```

**Comment by mauri870** [comment]
You need install a http client for handle the requests. You can found all supported http clients [here](https://packagist.org/providers/php-http/client-implementation).
Remove guzzle from your project and repeat the installation proccess, if not work try require a lower version of guzzle or another http client instead.

**Comment by mbarwick83** [comment]
umm, which one? I tried Guzzle6Adapter. Got more errors trying to install you library. I removed Guzzle6 before hand (which I need btw for Laravel).

**Comment by mauri870** [comment]
The proposal of psr-7 is to standardise the http messages , so any package on the link  should work. Try require httplug and one of the http clients before require the happyr package

**Comment by Nyholm** [comment]
I've made an update to the readme. Have a look at https://github.com/Happyr/LinkedIn-API-client/pull/94

**Comment by Nyholm** [comment]
Version 0.7.1 is using `php-http/discovery:0.9` which makes Puli optional. The Readme has also been improved on how you install a http client.
