### ISSUE TITLE
 'Puli Factory is not available' 

### ISSUE THREAD

**Issue by gautam2688** [Happyr/LinkedIn-API-client#98]
I am getting  'Puli Factory is not available'  error. How to solve it. please help me asap.
![social linkedin linkedin api client master](https://cloud.githubusercontent.com/assets/17717969/13593901/a94a6046-e525-11e5-9108-1562c066bae0.png)

**Comment by Nyholm** [comment]
Thank you for this issue. Have you read this section of the readme: https://github.com/Happyr/LinkedIn-API-client#finding-the-http-client

**Comment by gautam2688** [comment]
Same code work on Ubuntu but not on linux. After successfull execution on linux system, i just copy and paste code on windows system and getting same error.

Ubuntu system PHP Version is 5.5.9 
Windows PHP Version is 5.5.2.

**Comment by Nyholm** [comment]
So, on your windows environment, have you added the required Puli packages (including `"puli/composer-plugin": "^1.0.0-beta9",`) and then run `composer update`?

> Will you plz provide me complete source code link to my email address.

Not too sure what you mean by that..

**Comment by gautam2688** [comment]
Yes i have added and and getting same error.

**Comment by Nyholm** [comment]
Not sure why it does not work on Windows. Try not using auto discovery and and add the client and message factory yourself.

**Comment by gautam2688** [comment]
Ok Thanks @Nyholm
