### ISSUE TITLE
Unable to use API-client

### ISSUE THREAD

**Issue by dirkschaap** [Happyr/LinkedIn-API-client#99]
Hello, after giving authorisation I get the following error:

Fatal error: Uncaught exception 'RuntimeException' with message 'Puli Factory is not available' in /Users/Dirk/Develop/www/pebbler/sites/rezelman/dashboard/vendor/php-http/discovery/src/ClassDiscovery.php:32 Stack trace: #0 /Users/Dirk/Develop/www/pebbler/sites/rezelman/dashboard/vendor/php-http/discovery/src/ClassDiscovery.php(79): Http\Discovery\ClassDiscovery::getPuliFactory() #1 /Users/Dirk/Develop/www/pebbler/sites/rezelman/dashboard/vendor/php-http/discovery/src/ClassDiscovery.php(99): Http\Discovery...

Since I didn't use composer.phar before I have no clue how to solve this. I followed the install-instruction and used the demo-code for authentication. 
Can someone point me out how to solve this?

Thanks in advance.

Dirk Schaap

**Comment by Nyholm** [comment]
Hey. 
I would recommend you to use composer. It is a great tool that has revolutionized PHP. 

I will (within the coming weeks) review the documentation and make sure it is easy to understand and follow. So please give me feedback. But composer is a hard requirement. =)

**Comment by dirkschaap** [comment]
Hey,
I installed composer and did use it since it is recommended. However, I didn't use it before and now I run into this fatal error. Maybe the last part of the error message gives a clue...

happyr/linkedin-api-client/src/Http/RequestManager.php(34 in /Users/Dirk/Develop/www/pebbler/sites/rezelman/dashboard/vendor/php-http/discovery/src/ClassDiscovery.php on line 32

Regarding the manual:
Since I didn't have any experience with composer it took me a lot of time to get it running with only the line: _composer require happyr/linkedin-api-client_. With only this line it gave some errors...

**Comment by Nyholm** [comment]
It looks like you are on the right way. Read https://github.com/Happyr/LinkedIn-API-client#installation and https://github.com/Happyr/LinkedIn-API-client#finding-the-http-client and you will understand that you need to tell the LinkedIn client what library you use for sending HTTP messages. Ie you need to 

```php
$linkedIn=new Happyr\LinkedIn\LinkedIn('app_id', 'app_secret');
$linkedIn->setHttpClient(new \Http\Adapter\Guzzle6\Client());
$linkedIn->setHttpMessageFactory(new Http\Message\MessageFactory\GuzzleMessageFactory());
```

**Comment by dirkschaap** [comment]
Hi Nyholm,

Thanks for your help!! I got it working!
